name: CI

on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '>=1.21.1'
      - run: |
          sudo sysctl -w fs.file-max="2000500"
          sudo sysctl -w fs.nr_open="2000500"
          sudo sysctl -w net.nf_conntrack_max="2000500"
          sudo sysctl -w net.core.rmem_max="67108864"
          sudo sysctl -w net.core.wmem_max="67108864"
          sudo sysctl -w net.core.netdev_max_backlog="30000"
          sudo sysctl -w net.core.somaxconn="2048"
          sudo sysctl -w net.ipv4.ip_local_port_range="1024 65535"
          sudo sysctl -w net.ipv4.tcp_rmem="4096 87380 33554432"
          sudo sysctl -w net.ipv4.tcp_wmem="4096 65536 33554432"
          sudo sysctl -w net.ipv4.tcp_moderate_rcvbuf="1"
          sudo sysctl -w net.ipv4.tcp_fin_timeout="7"
          sudo sysctl -w net.ipv4.tcp_slow_start_after_idle="0"
          sudo sysctl -w net.ipv4.tcp_fack="1"
          sudo sysctl -w net.ipv4.tcp_window_scaling="1"
          sudo sysctl -w net.ipv4.tcp_max_syn_backlog="2048"
          sudo sysctl -w net.ipv4.tcp_tw_reuse="1"
      - run: AUTOBAHN=1 go test -v ./...